# fly.toml app configuration file generated for pycon-discord-bot on 2023-05-21T23:15:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pycon-discord-bot"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
